# Generated by Django 2.0.7 on 2018-11-26 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20181125_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='replay',
            new_name='reply',
        ),
    ]
